"""add conversation_summary and flow_story cache columns

Revision ID: cc02e5909673
Revises: 79419797551a
Create Date: 2026-07-11 17:45:39.435162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc02e5909673'
down_revision: Union[str, Sequence[str], None] = '79419797551a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('architectures', sa.Column('flow_story', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('requirements', sa.Column('conversation_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'conversation_summary')
    op.drop_column('architectures', 'flow_story')
    # ### end Alembic commands ###
