import LegalPageShell from "@/app/components/LegalPageShell";
import { SUPPORT_EMAIL } from "@/lib/legal-pages";

export const metadata = { title: "Terms of Service — Archwise" };

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated="July 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of Archwise (&quot;the
        Service&quot;), a tool that turns a plain-language product idea into a reasoned multi-cloud
        architecture. By creating an account or using the Service, you agree to these Terms.
      </p>

      <h2>Who operates this service</h2>
      <p>
        Archwise is currently built and operated by an individual, not a registered company. This
        is an early-stage, independently-run service — these Terms are written to be honest about
        that rather than imply a level of corporate formality that doesn&apos;t exist yet. Archwise
        is offered as a global service and is not limited to users in any one country.
      </p>

      <h2>Your account</h2>
      <p>
        You&apos;re responsible for keeping your login credentials secure and for all activity
        under your account. Let us know at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> if you believe your account has been
        compromised.
      </p>

      <h2>Free and paid access</h2>
      <p>
        Archwise offers a free tier with limited usage so you can fully try the product, and a paid
        subscription with unlimited usage. Current limits and pricing are described on our{" "}
        <a href="/pricing">Pricing</a> page. Payment terms, billing cycles, and cancellation are
        covered in our <a href="/refund-policy">Refund Policy</a>.
      </p>

      <h2>AI-generated content — please review before relying on it</h2>
      <p>
        Architectures, cost estimates, security findings, and infrastructure code generated by
        Archwise are produced by AI models combined with deterministic rules, and are meant as a
        strong starting point for your own engineering judgment — <strong>not</strong> as a
        guarantee of correctness, completeness, security, or production-readiness. Always review
        generated output, especially security and compliance findings and any infrastructure code,
        before deploying it or relying on it for a real system.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Using the Service to break the law, abuse or circumvent usage limits, attack or disrupt the
        Service, or generate content for harmful purposes is not allowed. See our full{" "}
        <a href="/acceptable-use">Acceptable Use Policy</a> for details.
      </p>

      <h2>Your content</h2>
      <p>
        You own the product ideas, requirements, and architectures you create in Archwise. We don&apos;t
        claim ownership over anything you generate. We do use your inputs to operate the Service —
        including sending relevant parts of your conversation to third-party AI model providers to
        generate responses, as described in our <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>Disclaimers and limitation of liability</h2>
      <p>
        The Service is provided &quot;as is,&quot; without warranties of any kind. To the fullest
        extent permitted by law, Archwise and its operator are not liable for indirect, incidental,
        or consequential damages arising from your use of the Service, including decisions made
        based on AI-generated output.
      </p>

      <h2>Changes to the Service or these Terms</h2>
      <p>
        Archwise is actively developed and these Terms may change as the product does. We&apos;ll
        update the date at the top of this page when that happens. Continuing to use the Service
        after a change means you accept the updated Terms.
      </p>

      <h2>Governing law and disputes</h2>
      <p>
        Because Archwise is currently operated by an individual without a registered legal entity,
        these Terms don&apos;t designate the courts of a specific country as having sole
        jurisdiction. If a dispute arises, we ask that you reach out to{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> first so we can try to resolve it
        directly and amicably. This section will be updated with formal jurisdiction and dispute-
        resolution terms once Archwise operates under a registered business entity.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms? Reach us at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalPageShell>
  );
}
